name: ServerSystem
version: 1.0
author: IchMagOmasKekse
api-version: 1.16

main: me.ichmagomaskekse.de.ServerSystem
commands:
#Lobby-Commands
  lobby:
    description: 'Teleports you to lobby spawn'
  setlobby:
    description: 'Sets the lobby spawn'
#Money-Commands
  money:
    description: 'Maincommand for the money system. Use /money help for help'
#Darkforge-Commands
  darkforge:
    description: 'Maincommand for the darkforge system. Use /darkforge to get a creator for creating a darkforge block'